actions:
  # já existe, mas aqui vai a versão alinhada com seus anchors
  open_item:
    steps:
      - {type: click, anchor: search_box}
      - {type: type_clear}
      - {type: type_text, text: "<item_name>"}
      - {type: sleep_ms, ms: 250}
      - {type: click, anchor: results_zone}
      - {type: sleep_ms, ms: 300}

  open_place_buy:
    steps:
      - {type: click, anchor: place_buy_button}
      - {type: sleep_ms, ms: 250}

  open_place_sell:
    steps:
      - {type: click, anchor: place_sell_button}
      - {type: sleep_ms, ms: 250}

  # preencher e confirmar (compartilhado p/ buy/sell modais)
  fill_order_and_confirm:
    steps:
      - {type: click, anchor: unit_price_input}
      - {type: type_clear}
      - {type: type_text, text: "<unit_price>"}   # exemplo: "1.23"
      - {type: click, anchor: quantity_input}
      - {type: type_clear}
      - {type: type_text, text: "<quantity>"}     # exemplo: "100"
      - {type: sleep_ms, ms: 200}
      - {type: click, anchor: confirm_button}
      - {type: sleep_ms, ms: 300}
