profiles:
  "2560x1440@100%":
    anchors:
      market_title: {x: 0.50, y: 0.08, w: 0.20, h: 0.05}
      header_row:   {x: 0.10, y: 0.16, w: 0.80, h: 0.05}   # área que mostra "Buy Orders" / "Sell Orders"
      search_box:   {x: 0.25, y: 0.12, w: 0.30, h: 0.05}   # campo de pesquisa global do market
      results_zone: {x: 0.25, y: 0.17, w: 0.50, h: 0.30}   # lista de resultados após digitar
      buy_tab:      {x: 0.12, y: 0.18, w: 0.08, h: 0.05}   # aba "Buy" (ajuste!)
      sell_tab:     {x: 0.21, y: 0.18, w: 0.08, h: 0.05}   # aba "Sell" (ajuste!)
      category_menu:{x: 0.08, y: 0.22, w: 0.10, h: 0.60}   # AJUSTE: região do menu lateral
      category_ores:{x: 0.10, y: 0.30, w: 0.18, h: 0.04}   # AJUSTE: linha/botão "Ores" dentro do menu
      list_zone:    {x: 0.56, y: 0.22, w: 0.39, h: 0.69}   # lista da direita (SELL)
      item_back_btn:     {x: 0.16, y: 0.28, w: 0.06, h: 0.05}  # (opcional) botão "Back"
      place_buy_button:  {x: 0.15, y: 0.58, w: 0.22, h: 0.06}  # "Place Buy Order"
      buy_panel_zone:    {x: 0.62, y: 0.12, w: 0.34, h: 0.32}  # área rolável do painel
      buy_panel_close:   {x: 0.95, y: 0.10, w: 0.02, h: 0.03}  # (se tiver "X" visível)
      my_orders_zone:    {x: 0.12, y: 0.26, w: 0.76, h: 0.60}   # AJUSTE: área da grade "MY ORDERS"
      footer_zone:  {x: 0.10, y: 0.90, w: 0.80, h: 0.06}
    columns:
      name:  {x: 0.02, w: 0.38}
      price: {x: 0.47, w: 0.14}
      qty:   {x: 0.87, w: 0.10}
    buy_panel_columns:
      price: {x: 0.06, w: 0.22}
      qty:   {x: 0.78, w: 0.18}
    my_orders_columns:
      price:         {x: 0.56, w: 0.14}
      qty_remaining: {x: 0.74, w: 0.12}
      item_name:     {x: 0.08, w: 0.42}
      side:          {x: 0.02, w: 0.05}
    scroll:
      step_pixels: 240
      pause_ms: 150
    buy_panel_scroll:
      step_pixels: 180
      pause_ms: 150
    search:
      input: {x: 0.32, y: 0.14, w: 0.18, h: 0.04}
      first_result: {x: 0.18, y: 0.27, w: 0.64, h: 0.05}
      pause_before_focus_ms: 150
      pause_after_clear_ms: 80
      type_interval_ms: 28
      pause_before_submit_ms: 120
      pause_before_result_click_ms: 220
      pause_after_action_ms: 260
